name: Salesforce Code Analyzer Workflow

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  salesforce-code-analyzer-workflow:
    permissions:
      contents: read
      security-events: write # Added this back in case you want SARIF later
      actions: read
      checks: write 
      
    runs-on: ubuntu-latest

    steps:
      - name: Check out files
        uses: actions/checkout@v5

      - name: Ensure node v20.9.0 or greater
        uses: actions/setup-node@v5
        with:
          node-version: '>=20.9.0'
     
      - name: Ensure java v11 or greater
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Ensure python v3.10 or greater
        uses: actions/setup-python@v6
        with:
          python-version: '>=3.10'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Latest Salesforce Code Analyzer CLI Plugin
        run: sf plugins install code-analyzer@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
          run-arguments: --workspace . --view detail --output-file sfca_results.html --output-file sfca_results.json
          results-artifact-name: salesforce-code-analyzer-results

      - name: Upload Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: analysis-reports
          path: |
            sfca_results.html
            sfca_results.json

      - name: Fail on Critical/High Violations (All Files)
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev2-violations > 0
        run: |
          echo "Build failed due to Severity 1 or 2 violations."
          exit 1
